### ISSUE TITLE
Doc ?

### ISSUE THREAD

**Issue by olup** [LoaderB0T/node-terminal-simulator#5]
Hey ! 

There isn't much doc :-). 

But from what I gather this lets you feed some terminal output and get a string representation of the terminal ? Like, feeding what `nano` is giving me when I interact with it and get a array of string representation of my terminal view, including what ansi sequence are doing ?

If that s so, this project would be of use to me !

**Comment by LoaderB0T** [comment]
@olup Hi there, thanks for taking your time looking at this repo :)

You are right with both! I really have to write some documentation at some point, never really thought anyone would find or need this repo ^^

Yes, the idea of this repo is that you create an instance of the Terminal class with a specific width and height. And then you for example manually send strings to the [write](https://github.com/LoaderB0T/node-terminal-emulator/blob/bb0d5f28ed40e5c11bbbda406fc9e9a9eec6a61d/src/models/terminal.ts#L26) method. This text can contain some supported ANSI espace codes and they will be handled like they are in the actual terminal (or at least as close and accurate as I was able to get it until now).

You can also use the [redirectStdout](https://github.com/LoaderB0T/node-terminal-emulator/blob/bb0d5f28ed40e5c11bbbda406fc9e9a9eec6a61d/src/models/terminal.ts#L36) method. Then everything to stdout will automatically be picked up by the simulated terminal.

The [sendKey](https://github.com/LoaderB0T/node-terminal-emulator/blob/bb0d5f28ed40e5c11bbbda406fc9e9a9eec6a61d/src/models/terminal.ts#L30) and [sentText](https://github.com/LoaderB0T/node-terminal-emulator/blob/bb0d5f28ed40e5c11bbbda406fc9e9a9eec6a61d/src/models/terminal.ts#L34) methods can be used to simulate key presses by the user in the terminal.

There is only a subset of escape codes supported. Colors are one of the big missing features. I tried for a while but gave up on it because I could not find a reasonably simple solution for now.

I am more than happy to accept PRs that fit the concept of this lib :)

If you need any more specific help, feel free to hit me up any time and I will try to write some docs soon-ish.

Edit:

Oh and keep in mind that I work in a windows environment. The few tests are also executed on Ubuntu, but the Terminal may behave differently on UNIX systems in the first place...

**Comment by LoaderB0T** [comment]
Hi there,

it's been a while but I finally polished the readme, added an example, and added inline documentation to the exposed methods.

Feel free to come back to me with any further questions.
